### ISSUE TITLE
The title spelling

### ISSUE THREAD

**Issue by paul-cares** [DanPorter/Dans_Diffraction#16]
Hi Dan, 

On main page: https://pypi.org/project/Dans-Diffraction/ check the spelling (missing "r"):
![image](https://github.com/DanPorter/Dans_Diffraction/assets/124775492/60c17f1e-aaf5-4ce9-b606-273fe32b4d4b)

Thanks for the code!
Paul.

**Comment by DanPorter** [comment]
Ha! Not sure how I missed that one all these years. Thank you!
Fixed in version 3.2, also found a few other offenders in the code.
