### ISSUE TITLE
DOI or citation

### ISSUE THREAD

**Issue by AndreEbel** [DanPorter/Dans_Diffraction#4]
Hi, 

I used your package and it worked fine for my use. 
I may publish my work at the end of the process. 
Do you have any idea about how I can cite your work ? 

Thanks

**Comment by DanPorter** [comment]
Hi AndreEbel,

Thanks very much for your message, it's great to hear my software has been useful! May I ask what parts you have used and what you were working on? I

I'm currently in the process of creating a published version that will have a DOI you can use. I'm still waiting to hear back from my employer about which open source licence to use, but I'll try and expedite the process and try to get you something next week (or possibly the week after).

Best wishes,

Dan

**Comment by AndreEbel** [comment]
Thanks for the early answer ! 

I used the very basic functionnalities of your package for indexing diffractograms obtained at different temperatures (HT-XRD). I was looking for a python tool so that i could do all my data processing and plotting in jupyter and I found your package. 

After creating a Crystal object using .cif file, I use Cell.all_hkl,  Scatter.intensity and Cell.tth to compute hkl, intensities and diffraction angles for different energies modifying Scatter._energy_kev property. 
Then I compare them with experimental diffractograms obtained. 
I also play with the cell parameter Cell.latt to take into account the effect of temperature on the lattice parameter.

So far it works well for this basic use. 

Good to hear this process of publication is moving forward ! 
Let us know when this will be completed so that we could properly cite your work. 

André

**Comment by AndreEbel** [comment]
Hi Dan, 

Anything new about this ? 

André

**Comment by DanPorter** [comment]
Hi André,

Apologies for the delay in reply, it took me a bit longer than anticipated to sort out the licencing, but all sorted now and fully open source.

There is now a DOI you can use to cite the software: https://doi.org/10.5281/zenodo.3859501

Best of luck with your publication, and do let me know if you have any problems.

Best wishes,

Dan

**Comment by AndreEbel** [comment]
Thanks Dan for your work.

It's good to be able to cite your package properly now.

I will definitely let you know I have any troubles.

André
________________________________
De : Dan Porter [notifications@github.com]
Envoyé : mercredi 27 mai 2020 12:16
À : DanPorter/Dans_Diffraction
Cc : EBEL André; Author
Objet : Re: [DanPorter/Dans_Diffraction] DOI or citation (#4)


Hi André,

Apologies for the delay in reply, it took me a bit longer than anticipated to sort out the licencing, but all sorted now and fully open source.

There is now a DOI you can use to cite the software: https://doi.org/10.5281/zenodo.3859501

Best of luck with your publication, and do let me know if you have any problems.

Best wishes,

Dan
